CoffeeShop/Controllers/BaristaController.cs
using CoffeeShop.Dal;
using CoffeeShop.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace CoffeeShop.Controllers
{
    public class BaristaController : Controller
    {
        private OrdersDal orders = new OrdersDal();
        private drinksDal drinks = new drinksDal();
        private UserDal us = new UserDal();

        // GET: Barista
        public ActionResult Index()
        {

            return View(orders.orders.ToList<Order>());
        }

        public ActionResult SearchOrders()
        {
            List<Order> ord = orders.orders.ToList<Order>();
            List<string> Names = null;
            String searchedValue = Request.Form["searchInput"];
            if(searchedValue.Equals(""))
                return PartialView("search", ord);
            bool z = us.Users.AsEnumerable().Where(u => u.name.Contains(searchedValue)).ToList().Count > 0;
            if (z)
            {
                Names = us.Users.Where(u => u.name.ToLower().Contains(searchedValue.ToLower())).Select(u => u.uid.ToString()).ToList();

                
            }
            
            if(Names != null)
                ord = (from x in orders.orders where Names.Any(s => s.ToLower().Contains(x.uid.ToLower())) select x).ToList<Order>();
            else
                ord = (from x in orders.orders where x.uid.ToLower().Contains(searchedValue.ToLower()) select x).ToList<Order>();


            return PartialView("search", ord);
        }

        public ActionResult Confirm()
        {
           
            string oid = Request.Form["oid"];
            string strcon = ConfigurationManager.ConnectionStrings["OrdersDal"].ConnectionString;
            SqlConnection con = new SqlConnection(strcon);
            if (con.State == System.Data.ConnectionState.Closed)
                con.Open();           
            SqlCommand cmd = new SqlCommand(" UPDATE Orders  SET confirm = 1 Where id = " + oid + "", con);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                //updated success                 
            }
            List<Order> ord = orders.orders.ToList<Order>();
            return PartialView("search",ord);
        }

        public List<Drink> OrdersPerOrder(Order o)
        {
            List<Drink> l = new List<Drink>();

            return l;
        }

        [HttpPost]
        public ActionResult UpdateOrder()
        {
            string oid = Request.Form["oid"];
            string did = Request.Form["did"];
            string quant = Request.Form["quantity"];
            float price = calcTotalPrice(int.Parse(oid), int.Parse(did),int.Parse(quant));

            string strcon = ConfigurationManager.ConnectionStrings["OrdersDal"].ConnectionString;
            SqlConnection con = new SqlConnection(strcon);
            if (con.State == System.Data.ConnectionState.Closed)
                con.Open();
            SqlCommand cmd = new SqlCommand(" UPDATE Orders  SET amount = " + quant + ", price = '" + price + "'  Where id = " + oid + " And did = " + did + "", con);
            SqlDataReader dr = cmd.ExecuteReader();
            dr.Close();
            cmd = new SqlCommand(" UPDATE Orders  SET price = '" + price + "'  Where id = " + oid + "", con);
            dr = cmd.ExecuteReader();
            //ViewBag.str = oid;
            List<Order> ord = orders.orders.ToList<Order>();
           //ystem.Threading.Thread.Sleep(1000);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteOrder(int dx, int dy)
        {
            UpdateOrder(dx, dy);
            orders.orders.Remove(orders.orders.Find(dx,dy));
            orders.SaveChanges();
            return RedirectToAction("Index");
        }

        public float calcTotalPrice(int oid, int did,int quant)
        {

            Order ord = orders.orders.Find(oid, did);
            Drink d = drinks.Drink.Find(did);
            int prevQuant = ord.amount;
            float total = float.Parse(ord.price);
            if(quant > prevQuant)
            {
                total = float.Parse(ord.price) + float.Parse(d.price) * (quant-prevQuant);
            }
            else if(quant < prevQuant)
            {
                total = float.Parse(ord.price) + float.Parse(d.price) * (quant - prevQuant);
            }

            return total;

        }

        public void UpdateOrder(int id, int did)
        {

            Order ord = orders.orders.Find(id, did);
            float price = float.Parse(ord.price) - float.Parse(drinks.Drink.Find(did).price) * ord.amount;
            string strcon = ConfigurationManager.ConnectionStrings["OrdersDal"].ConnectionString;
            SqlConnection con = new SqlConnection(strcon);
            if (con.State == System.Data.ConnectionState.Closed)
                con.Open();
            SqlCommand cmd = new SqlCommand(" UPDATE Orders  SET price = '" + price + "'  Where id = " + id + "", con);
            SqlDataReader dr = cmd.ExecuteReader();
            
        }


    }
}

CoffeeShop/Views/Barista/Index.cshtml
@model List<Order>

@{ ViewBag.Title = "Index";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

@using CoffeeShop.Models;
@{ ViewBag.Title = "Index";
                Layout = "~/Views/Shared/_Layout.cshtml";
                AjaxOptions ajaxOpt = new AjaxOptions
                {
                    HttpMethod = "POST",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "unreff"
                };

                ViewBag.ajax = ajaxOpt;
                List<Order> ord = Model; }




<link href="~/Content/css-admin/style.css" rel="stylesheet" />
<link href="~/Content/css-admin/bootstrap.min.css" rel="stylesheet" />
@*<link href="~/Content/css-admin/owl.carousel.min.css" rel="stylesheet" />*@

<section class="ftco-menu mb-5 pb-5">
    <div class="container">
        <div class="col-lg-12 ftco-animate p-md-5">
            <div class="row">
                <div class="col-md-12 nav-link-wrap mb-5">
                    <div class="nav ftco-animate nav-pills justify-content-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        <a class="nav-link active" id="v-pills-0-tab" data-toggle="pill" href="#v-pills-0" role="tab" aria-controls="v-pills-0" aria-selected="true">Orders</a>
                    </div>
                    <!--Add Users ----Search Users---- Show Users-->
                    <div class="tab-content ftco-animate" id="v-pills-tabContent">
                        <div class="tab-pane fade show active" id="v-pills-0" role="tabpanel" aria-labelledby="v-pills-0-tab">
                            <br />
                            <!--Search Users-->
                            <div class="col-md-17 mb-7" style="width: 30%; margin: auto;">
                                @using (Ajax.BeginForm("SearchOrders", "Barista", null, ajaxOpt, new { id = "searchrecords" }))
                                {
                    <div class="row d-md-flex col-15 ">
                        <div class="input-group">
                            <input id="search" name="searchInput" type="text"  class="form-control rounded" placeholder="Search user" aria-label="Search"
                                   aria-describedby="search-addon" />
                            <button type="submit" class="btn btn-primary btn-outline-primary">search</button>
                        </div>
                        @*onchange="$('#searchrecords').submit()"*@
                    </div>}
                            </div>
                            <br />
                            <div id="unreff">
                                @Html.Partial("/Views/Barista/search.cshtml", ord);
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@*<script src="~/Scripts/js-admin/popper.min.js"></script>
    <script src="~/Scripts/js-admin/bootstrap.min.js"></script>
    <script src="~/Scripts/js-admin/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/js-admin/main.js"></script>*@

@if (Session["email"] == null || Session["role"].ToString() != "barista")
{

<script>
    alert("You Are Not Authorize!");
    document.querySelector('#auth').style.display = 'none';
</script>
}

CoffeeShop/Views/Barista/search.cshtml
@model List<Order>
@using CoffeeShop.Models
@using CoffeeShop.Dal
@using Microsoft.Ajax.Utilities
@{ AjaxOptions ajaxOptic = new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "unref12"
    };

    AjaxOptions ajaxConfirm = new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "unreff"
    };

    AjaxOptions ajaxUpdt = new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "unreffs"
    };


    AjaxOptions s = (AjaxOptions)ViewBag.ajax;
    List<Order> ord = Model;
    drinksDal dr = new drinksDal();
    Dictionary<List<Drink>, float> d = new Dictionary<List<Drink>, float>(ord.Count);

    for (int i = 0; i < ord.Count; i++)
    {
        float totalPrice = 0;
        List<Drink> drinks = new List<Drink>();
        int j = i;
        while ((j < ord.Count && ord[i].id == ord[j].id) || j == i)
        {
            Drink drink = (Drink)dr.Drink.Find(ord[j].did);
            totalPrice += float.Parse(drink.price) * ord[j].amount;
            drinks.Add(drink);
            j++;
        }
        i = j - 1;

        d.Add(drinks, totalPrice);
    }
    int unique = 0;
    int countDups = 0;
    int dups = 0;
    int id_table = 0;
    for (int i = 0; i < ord.Count; i++)
    {
        if (i != 0 && ord[i].id == ord[i - 1].id)
        {
            dups++;
        }
    }
    int rows = ord.Count - dups;

    UserDal userDB = new UserDal();



    } <!--Show Users-->




<div class="table-responsive custom-table-responsive ">
    <table class="table custom-table ">

        <thead>
            <tr>
                <th scope="col">
                    <label class="control control--checkbox">
                        <input id="lap" type="checkbox" class="js-check-all" />
                        <div class="control__indicator"></div>
                    </label>
                </th>
                <th scope="col">OrderID</th>
                <th scope="col">Date</th>
                <th scope="col">User</th>
                <th scope="col">Vip</th>
                <th scope="col">Total Price</th>
                <th scope="col">Confirm Payment</th>
                <th scope="col">TableID</th>
                <th scope="col">Table Date</th>
                <th scope="col"></th>
            </tr>
        </thead>

        @for (int i = 0; i < ord.Count; i++)
        {
            
            if (i != 0 && ord[i].id == ord[i - 1].id)
            {
                countDups++;

                continue;
            }
            if ((i != 0 && ord[i].id != ord[i - 1].id) || i == 0)
            {
      

<tr scope="row" id="@rows" class="prod_rows">
    <th class="product-remove" scope="row">
        <label class="control control--checkbox">            
                <input id="@("colapse" + i)" type="checkbox" />            
            <div class="control__indicator"></div>
        </label>
    </th>
    <td>@ord[i].id </td>
    <td>@ord[i].date </td>
    @if (!ord[i].uid.Contains("Guest")) {
        user u = userDB.Users.Find(int.Parse(ord[i].uid));
        <td>@u.name </td>
        <td>@u.isVip </td>    
    }
      else { 
        <td>@ord[i].uid</td>
        <td>Guest</td>
        
    }
    
    
    
    
    <td>@ord[i].price $</td>

    <td>@ord[i].confirm.ToString()</td>
    @if (!ord[i].take)
    {
        if(ord[i].tid > 0) { 
            <td>@ord[i].tid </td>         
        }
        else { 
            <td></td>
        }
                        <td>@ord[i].tdate </td> }
                                            else
                                            {
                        <td></td>
                                                <td> </td>}

                <td >
        @if (!ord[i].confirm)
        {
            using (Ajax.BeginForm("Confirm", "Barista", ajaxConfirm))
            {
                <input name="oid" value="@ord[i].id" style="display:none" />
                                            <input name="did" value="@ord[i].did" style="display:none" />
                                                                        <input name="" type="submit" class="btn btn-outline-success" value="Confirm" />
            }
        }
        else
        {
        <input name="" type="submit" class="btn btn-outline-success" value="Confirmed" disabled />                 
        }
                </td> 
    

</tr>
                for (int j = 0, k = i - countDups; j < d.ElementAt(k).Key.Count; j++)
                {
    <tr id="@("" + id_table + "-" + j + "prod")" scope="row">
        
        <td class="product-remove">@Html.ActionLink(" ", "DeleteOrder", new { dx = ord[i].id, dy = d.ElementAt(k).Key[j].id }, new { @class = "icon-close" }) </td>

        @if (d.ElementAt(k).Key[j].isBusiness)
        {
            if (d.ElementAt(k).Key[j].name.Contains("Burger"))
            {

    <td class="image-prod"><div class="img" style="background-image: url(../../images/burger-@(d.ElementAt(k).Key[j].img).jpg);"></div></td>
 }
else
{
    <td class="image-prod"><div class="img" style="background-image: url(../../images/dish-@(d.ElementAt(k).Key[j].img).jpg);"></div></td>
}
}
        @if (!d.ElementAt(k).Key[j].isAlcohol && !d.ElementAt(k).Key[j].isBusiness)
        {
    <td class="image-prod"><div class="img" style="background-image: url(../../images/menu-@(d.ElementAt(k).Key[j].img).jpg);"></div></td>
}
        @if (d.ElementAt(k).Key[j].isAlcohol && !d.ElementAt(k).Key[j].isBusiness)
        {
    <td class="image-prod"><div class="img" style="background-image: url(../../images/drink-@(d.ElementAt(k).Key[j].img).jpg);"></div></td>
}


        <td class="product-name">
            <h3>@d.ElementAt(k).Key[j].name</h3>
            @*<p>Far far away, behind the word mountains, far from the countries</p>*@
        </td>
        <td class="price">@d.ElementAt(k).Key[j].price$</td>
        <td></td>
        <td class="quantity">
            @*@using (Ajax.BeginForm("UpdateOrder", "Barista", null, ajaxConfirm, new { id = "newPrice" + unique }))
            {

                <div class="input-group mb-2">
                    <input id="did" value="@d.ElementAt(k).Key[j].id" style="display:none" name="did" value="5" />
                    <input id="oid" value="@ord[i].id" style="display:none" name="oid" value="5" />
                    <input type="number" id="qua" start="1" step="1" onchange="$('#newPrice' + @unique);.trigger('submit')" name="quantity" class="quantity form-control input-number" value="@ord[i+j].amount" style="max-width:50%; margin-left:50px;" min="1"  />
                </div>
                        <input type="submit" class="btn btn-primary btn-outline-primary" value="Update"/>
                    <td>
                    </td>

            }*@

            <form action="Barista/UpdateOrder" method="post">

                <div class="input-group mb-2">
                    <input id="did" value="@d.ElementAt(k).Key[j].id" style="display:none" name="did" value="5" />
                    <input id="oid" value="@ord[i].id" style="display:none" name="oid" value="5" />
                    <input type="number" id="qua" start="1" step="1" onchange="$('#newPrice' + @unique);.trigger('submit')" name="quantity" class="quantity form-control input-number" value="@ord[i+j].amount" style="max-width:50%; margin-left:50px;" min="1" />
                </div>
                <td>
                    <input type="submit" class="btn btn-primary btn-outline-primary" value="Update" />
                </td>
            </form>
        </td>
        <td></td>
        <td></td>
    </tr><!-- END TR-->
                {unique++;}
                }
            }
            id_table++;
        }
        @{countDups = 0;}

    </table>
</div>

<h1>no users</h1>
<style>
    [id*=prod] {
        opacity: 0;
        display: none;
        transition: opacity 0.5s;
    }
</style>

<script>

    var prodSize = document.getElementsByClassName('prod_rows')[0].id;
    var prodlist = []
    for (var i = 0; i < prodSize; i++) {
        prodlist.push(document.querySelectorAll(`[id^="${i}-"]`))
    }
    var prod = document.querySelectorAll('[id^="prod"]');
    var colapse = document.querySelectorAll('[id^="colapse"]');


    for (var j = 0; j < colapse.length; j++) {
        (function (j) {
            colapse[j].addEventListener('change', function (event) {
                for (var k = 0; k < prodlist[j].length; k++) {
                    if (event.currentTarget.checked) {

                        prodlist[j][k].style.display = 'revert';
                        setTimeout(function ({ j, k }) {
                            console.log(prodlist[j][k]);
                            prodlist[j][k].style.opacity = '1';
                        }, 10, { j, k });

                    } else {
                        prodlist[j][k].style.opacity = '0';
                        setTimeout(function ({ j, k }) {
                            prodlist[j][k].style.display = 'none';
                        }, 500, { j, k });

                    }
                }
            }, false);
        })(j);
    }
    
</script>